### ISSUE TITLE
Providing invalid color while using large graph

### ISSUE THREAD

**Issue by ArindamK92** [kokkos/kokkos-kernels#1175]
I used the below command to use the code from kokkos-kernels/build/perf_test/graph folder to generate vertex color for a large scale graph ca-IMDB
`./graph_color --openmp 8 --algorithm COLORING_EB --amtx ca-IMDB_forKokkos.mtx --outputfile colorcolor_ca-IMDB_kokkos_VBBIT`

But it is generating a lot of invalid colors. E.g.
```
sed -n 365980p colorcolor_ca-IMDB_kokkos_VBBIT
2

sed -n 209198p colorcolor_ca-IMDB_kokkos_VBBIT
2
```
Both vertex 365980 and 209198 are colored with color 2. However, they are adjacent.
```
grep -n "365980 209198" ca-IMDB_forKokkos.mtx
798393:365980 209198
```

I tried with a single OpenMP thread also and got the same invalid color. I tried other algorithms such as COLORING_VBBIT also and got similar kinds of invalid colors.

**Comment by brian-kelley** [comment]
@ArindamK92 I downloaded this graph and it looks like it's nonsquare bipartite (428440x896308) - can you confirm that your file has the same dimensions? The KokkosKernels graph coloring just supports undirected graphs (so the adjacency matrix must be square and symmetric).

**Comment by ArindamK92** [comment]
$ head ca-IMDB_forKokkos.mtx
%%MatrixMarket matrix coordinate real general
896308 896308 3782463
405632 1
303789 2
364797 2
31020 3
240622 3
225433 4
117545 5
210080 6

Do you mean KokkosKernels will accept an input graph only if edge "a b" in a graph file imples there should be another edge "b a" also in the file?

**Comment by brian-kelley** [comment]
@ArindamK92 That's correct for a "general" structure MatrixMarket file. If instead of "general" it was "symmetric", then "a b" could appear in the file without "b a", but when the file gets loaded both entries would be inserted.

**Comment by ArindamK92** [comment]
ok. So, if I try to use ca-IMDB_forKokkos.mtx for KokkosKernel, will it work if I just change the first line to "%%MatrixMarket matrix coordinate real symmetric"? (I don't care if the graph becomes undirected from a directed version)

OR do I need to double the edges by adding the "b a" part?

**Comment by brian-kelley** [comment]
@ArindamK92 Yes. I just tried this to make sure and it worked (I added a call to verify the correctness of the coloring):
```
Time:0.0163754 Num colors:17 Num Phases:3
	1 1 1 1 2 2 4 1 1 1 1 1 1 1 2 1 1 1 1 2 ... ... ... 1 1 1 2 1 1 1 2 1 4 2 1 2 2 1 2 1 2 1 1 
Verifying coloring... 0 conflicts.
```
I'm thinking though, since this is a bipartite graph, where rows are movies and columns are actors, it would be more meaningful to do a bipartite coloring. By that I mean there is no real relationship between actor 1 and movie 1, but symmetrizing this graph assumes there is. With ca-IMDB.mtx being the original file ("general" and the dimensions being 428440x896308), you could do:
```
./graph_color_d2 --amtx ca-IMDB.mtx --cuda 0 --bipartite_rows --algorithm COLORING_D2_VB_BIT
```
to color movies (so that no 2 movies of the same color share an actor) or:
```
./graph_color_d2 --amtx ca-IMDB.mtx --cuda 0 --bipartite_cols --algorithm COLORING_D2_VB_BIT
```
to color actors (so that no 2 actors with same color appear in a movie together).

**Comment by ArindamK92** [comment]
Thank you so much for the help :)
