### ISSUE TITLE
Require CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON in CUDA, complex ON, ETI ON build

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#176]
See discussion here: https://github.com/trilinos/Trilinos/issues/2141

**Comment by ndellingwood** [comment]
@mhoemmen I have PR #149 up to check that `CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS=ON` for the CUDA, complex ON, ETI ON build, and if not tell users to enable this. 

From trilinos/Trilinos#2141 it seems the decision is to let users enable this CMake option rather than set it as default due to potential issues depending on combos of OS, CMake version and compiler [see NOTE bottom of TribitsBuildReference](https://tribits.org/doc/TribitsBuildReference.html#enabling-the-usage-of-resource-files-to-reduce-length-of-build-lines)

Is PR #149 sufficient to resolve this issue?

**Comment by ndellingwood** [comment]
Adding @srajama1 to discussion.

**Comment by mhoemmen** [comment]
@ndellingwood I left some comments on PR #149 that address your questions.  I would prefer that kokkos-kernels check for now, as long as that works for all tested host compiler options in CUDA builds.

**Comment by srajama1** [comment]
Based on the comments in the above referenced Trilinos issue and the comment about gfortran and CMake, let us just request the user to set it and reconfigure. I will add it to my list of annoyances and complain in about it on bad days :)

We should at least update the limited "documentation"  we have so whoever is enabling complex knows this ahead. Let us do that and push this.
