### ISSUE TITLE
Batched SVD returning incorrect results with CUDA

### ISSUE THREAD

**Issue by jacobmerson** [kokkos/kokkos-kernels#1786]
Running the `KokkosBatched::SerialSVD` in a parallel for loop with the `Cuda` backend gives incorrect results.

I have created a minimal reproducer here: https://github.com/jacobmerson/kokkosbatched-svd-error/blob/main/test.cc.

The example output is here: https://github.com/jacobmerson/kokkosbatched-svd-error/blob/main/example_output.txt

The singular values seem to match for the first entry, but in every other entry there are incorrect results with the `CUDA` backend. the results from the `Serial` backend match the results from scipy.

I have tested this with:
- Kokkos@48b34def1bf1cd48cfa1d2f155a766e04d36729f
- kokkos-kernels@b9c1bab7a8ae7c9413ad09f612f9011ff04a819e
- gcc@11.2.0
- nvcc@V11.4.152

@brian-kelley I'm tagging you because I see that you are the original author of the code.

**Comment by brian-kelley** [comment]
@jacobmerson Thanks a lot, the layout making a difference was a good hint. The issue turned out to be that the work array ``W`` needs to be contiguous, but it will be noncontiguous (strided) in the case of:
```
  Kokkos::View<Scalar * [N], Kokkos::LayoutLeft, memory_space> works("works", matrices.extent(0));
...
  auto work = Kokkos::subview(works, i, Kokkos::ALL());
```
If works is LayoutRight, then there's no problem because each row is contiguous in memory.
In #1793 , I added a compile-time check that the work view is contiguous, and added your reproducer as a new test.

**Comment by jacobmerson** [comment]
Great! Thanks for adding the compile time checks in.
