### ISSUE TITLE
Merge path doesn't zero out NaNs when beta=0

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#2166]
In spmv (y := alpha*Ax + beta*y) if y contains a nan on input and beta is zero, all its entries should be overwritten with zero rather than multipled by zero (preserving nans) before computing alpha*Ax.

The default native algorithm seems to do this, but merge path doesn't.
We should also test this systematically in the spmv unit tests.

**Comment by brian-kelley** [comment]
I think this is actually the same issue as #2010 which was closed with a workaround, but  I'll just leave this open instead of reopening that one

**Comment by cwpearson** [comment]
I think this is the offending line: https://github.com/kokkos/kokkos-kernels/blob/b87dc951f64463fe5d6d4d886c0496ee804b2715/sparse/impl/KokkosSparse_spmv_impl_merge.hpp#L312

If I'm reading `scal` correctly, it just just `y = beta * y` for this case, so if `y` is NaN it won't work.

The `Test_Sparse_spmv_bsr.hpp` file generates random vectors for tests, but those vectors do not include `NaN`, which is why this passes the tests.

**Comment by lucbv** [comment]
Then we probably want to have an if statement to check for `beta == 0` and call `Kokkos::deep_copy(y, 0);` in that case
