### ISSUE TITLE
Warning in IOUtils

### ISSUE THREAD

**Issue by srajama1** [kokkos/kokkos-kernels#481]
/ascldap/users/srajama/work_repos/kokkos-kernels-main/perf_test/sparse/KokkosSparse_block_pcg.cpp(495): here

/ascldap/users/srajama/work_repos/kokkos-kernels-main/example/buildlib/install/include/KokkosKernels_IOUtils.hpp(1037): warning: statement is unreachable
          detected during:
            instantiation of "int KokkosKernels::Impl::read_mtx(const char *, lno_t *, size_type *, size_type **, lno_t **, scalar_t **, __nv_bool, __nv_bool, __nv_bool) [with lno_t=int, size_type=int, scalar_t=double]" 
(1205): here
            instantiation of "void KokkosKernels::Impl::read_matrix(lno_t *, size_type *, size_type **, lno_t **, scalar_t **, const char *) [with lno_t=int, size_type=int, scalar_t=double]"

**Comment by brian-kelley** [comment]
@srajama1 What compiler were you using? I don't get the warning on GCC 7.4. I think your compiler is being way too clever, since std::is_integral<double>::value is false at compile time the "throw" branch is always taken.

I think I know how to fix it (make it an if-else instead of an if-fallthrough) but I want to be able to replicate it to know that I fixed it.

**Comment by srajama1** [comment]
I just use "source Trilinos/cmake/std/atdm/load-env.sh cuda-release-Pascal60" on white which gets gcc 7.2.0.

However, I use "-Wall -pedantic -Werror -O3 -g -Wshadow -Wsign-compare -Wtype-limits -Wuninitialized", may be that makes the difference.

**Comment by brian-kelley** [comment]
I replicated the warning and have a fix, running spot checks now.
