### ISSUE TITLE
Invalid coloring created in distance-2 graph coloring

### ISSUE THREAD

**Issue by cgcgcg** [kokkos/kokkos-kernels#501]
MueLu is using `COLORING_D2_SERIAL`, and the produced colors appear to be invalid. I checked this by hacking up the test `graph_verify_distance2_color` from `KokkosGraph_Distance2Color_impl.hpp` to not bug out for rectangular matrices. This occurred on lassen.

I can provide graphs and the produced colors.

**Comment by srajama1** [comment]
Oh man, yes please share the graphs with me.

**Comment by cgcgcg** [comment]
There might be some other issues in MueLu that we need to address first. Some of these dumped graphs look quite unsymmetric..

**Comment by brian-kelley** [comment]
@cgcgcg Even if the global graph is symmetric, is it possible that the local graph has remotes? The D2 coloring internally filters out remote vertices, but not columns. E.g. if numRows is 4, but row 2 is adjacent to {0,2,3,5}, then the D2 will try to access the rows/vertices adjacent to column 5, which will invalid since MueLu is passing in the same graph for both rows->cols and cols->rows.

**Comment by cgcgcg** [comment]
Even the local part was unsymmetric. We can filter out the off-rank entries.

**Comment by brian-kelley** [comment]
@cgcgcg This ended up being an issue with MueLu dropping entries asymmetrically, right? If it is a dist-2 bug it would be nice to fix it for the 3.0 snapshot.

**Comment by cgcgcg** [comment]
I believe that we can close this. The issue was that the matrix was badly scaled (very close to machine eps), and MueLu dropping was unsymmetric.
