### ISSUE TITLE
cuBLAS Cmake logic wrong?

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#777]
@jjwilke @ndellingwood 
While working with @cgcgcg on issue #775 on Lassen, I noticed that `cm_generate_makefile.bash` does not lead to a working configuration if I enable cuBLAS: `--with-tpls="cublas,cusparse"`.
If I enable cuSPARSE only things are working fine.
Simply modifying the CMakeLogic in `Cmake/Modules/FindTPLCUBLAS.cmake` to mirror what happens in the corresponding file for cuSPARSE resolves the issue.
I will open a PR to propose that change.

**Comment by ndellingwood** [comment]
Separate from the cmake logic aspects of this issue, the cm_generate_makefile requires also adding host-blas to the tpl list to get a working configuration when using cublas, so the script needs updating with better output messaging to indicate this; attempting to automatically enable a host blas tpl would be problematic on machines that do not have an install on the system path (for example our white testbed, where this issue is handled separately in our testing scripts), so I don't think that would be a good option. I'll put in a PR to update the script, sorry for the frustrations.

Linking comment here regarding the script issue for reference https://github.com/kokkos/kokkos-kernels/pull/778#issuecomment-666513890
